name: Deploy Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Plugin:
    name: Deploy-Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: |
            .
            !.DS_Store 
            !.stylelintrc.json 
            !.eslintrc 
            !.git 
            !.gitattributes 
            !.github 
            !.gitignore 
            !README.md 
            !node_modules 
            !package-lock.json 
            !package.json
            !phpcs.xml.dist 
            !scripts/
            !sass 
            !style.css.map 
            !yarn.lock
            !src/
            !node_modules/